192.168.250.21:
  :roles:
    - common
    - deploy_common
  :cpucores: 6
  :memory: 8
  :disksize: 300
  :interface: Ethernet0
  :ipaddress: 192.168.250.21
  :dnsserver: 192.168.250.1
  :defaultgw: 192.168.250.1
  :localuser: localuser
  :hostname: W2K19TGT
  :osrelease: Windows Server 2019 Standard
  :language: 日本語
  :LANG: en-US
  :LCID: 1033
  :proxyipaddress: 192.168.250.240:8080
  :domainname: test-card.corp
  :osedition: Microsoft Windows Server 2019 Starndard
  :currentbuild: 17763
  :releaseid: 1809
  :osversion: 4645
  
